Vibe tc 59 skille kolonnen sist oppdatert
navikt/veilarbvedtaksstotte pull request #135
Opened 2021-02-17 05:05 UTC by jeeveshmishranav

Hei,

Jeg har lagt ny kollonen og tests rundt denne database versjon endring. Vær så snill å ta en review.

Jeg er litt bekymret om kode indentasjon men det kan jeg ordne på vei. :-)

Hilsen,
Jeevesh

2021-02-17 10:41 UTC, matiasvinjevoll requested changes

2021-02-17 10:41 UTC, matiasvinjevoll commented on src/main/java/no/nav/veilarbvedtaksstotte/repository/VedtaksstotteRepository.java
> +                "UPDATE %s SET %s = ?, %s = ?, %s = ?, %s = CURRENT_TIMESTAMP, %s = CURRENT_TIMESTAMP, %s = true, %s = false WHERE %s = ?",
Her tenker jeg vi kun trenger å oppdatere `VEDTAK_FATTET`, og ikke `UTKAST_SIST_OPPDATERT`

2021-02-17 10:41 UTC, matiasvinjevoll commented on src/main/java/no/nav/veilarbvedtaksstotte/repository/VedtaksstotteRepository.java
> +                VEDTAK_TABLE, STATUS, UTKAST_SIST_OPPDATERT, GJELDENDE, VEDTAK_ID
Her må vi oppdatere `VEDTAK_FATTET` og ikke `UTKAST_SIST_OPPDATERT`

2021-02-17 10:41 UTC, matiasvinjevoll commented on src/main/java/no/nav/veilarbvedtaksstotte/service/VedtakStatusEndringService.java
> +                .setVedtakSendt(vedtak.getUtkastSistOppdatert())
Her skal det være `vedtak.getVedtakFattet()`, men den er ikke oppdatert på `vedtak`-objektet her. Tror metoden `vedtakSendt` på L:102 bør ta inn vedtak id og ikke `Vedtak` objekt, og slå opp i databasen.

2021-02-17 10:41 UTC, matiasvinjevoll commented on src/main/java/no/nav/veilarbvedtaksstotte/utils/VedtakUtils.java
> +                .filter(vedtak -> dato.isAfter(vedtak.getUtkastSistOppdatert()))
Her skal det være `vedtak.getVedtakFattet()`

2021-02-17 10:41 UTC, matiasvinjevoll commented on src/main/resources/db/migration/V23__skille kolonnen_SIST_OPPDATERT.sql
> +    ADD COLUMN VEDTAK_FATTET TIMESTAMP DEFAULT NULL;
Trenger man `DEFAULT NULL`? (er ikke det default oppførsel?)

2021-02-17 10:41 UTC, matiasvinjevoll commented on src/test/java/no/nav/veilarbvedtaksstotte/repository/FlywayDbMigrationTest.java
> +    @Test(expected = Exception.class)
Bør slå sammen testene og 1. migrere til v22, 2. legge inn data, f.eks. et utkast og et fattet vedtak. 3. migrere til v23/evt til siste. 4. hente ut data og gjøre sjekker på at migreringen er riktig.

2021-02-17 10:41 UTC, matiasvinjevoll commented on src/test/java/no/nav/veilarbvedtaksstotte/utils/SingletonPostgresContainer.java
> +    public static PostgresContainer init(String versjonPrefix) {
Ikke i bruk?

2021-02-26 13:06 UTC, matiasvinjevoll requested changes

2021-02-26 13:06 UTC, matiasvinjevoll commented on src/main/java/no/nav/veilarbvedtaksstotte/service/VedtakStatusEndringService.java
> +                .setVedtakSendt(vedtak.getUtkastSistOppdatert())
Denne må endres til `vedtak.getVedtakFattet()`

2021-03-04 13:52 UTC, jeeveshmishranav commented on src/main/java/no/nav/veilarbvedtaksstotte/service/VedtakStatusEndringService.java
> +                .setVedtakSendt(vedtak.getUtkastSistOppdatert())
metoden vedtakSendt på L:106 tar vedtakId og ikke vedtak objekt. Bruk av getVedtakFattet er nå på plass.

2021-03-05 10:24 UTC, matiasvinjevoll approved these changes

2021-03-05 11:06 UTC, merged